### ISSUE TITLE
nginx rework webserver misconfigured

### ISSUE THREAD

**Issue by Unkn0wn0x** [mhzawadi/invoiceplane#1]
First of all, great job for the rework with nginx!

I upgraded your docker image to the latest version, but it does not work out of the box.

The problem is, that nginx has a `default.conf` (directory `/etc/nginx/conf.d/`), which always return a 404 error on every request. Nginx will never use your `nginx_site.conf`.

By simply removing the file, `/etc/nginx/conf.d/default.conf` your image works as expected.

**Comment by mhzawadi** [comment]
Thanks for your feedback, I have updated the readme to reflect the use of the HOST_URL. I hope that sorts your issue, if not and please let me know.

```bash
$ docker run -ti -d -p 80:80 --name invoiceplane --link invoiceplane-mysql:mysql -e HOST_URL=127.0.0.1 mhzawadi/invoiceplane
```

We are linking the two containers and expose the HTTP port with a host URL of 127.0.0.1, you need to set the HOST_URL as Nginx uses this to accept incoming requests.

**Comment by Unkn0wn0x** [comment]
Thanks for your fast feedback.

That does not solve the problem, since the nginx has it's `default.conf` on startup which will prevent, that your `nginx_site.conf` will be processed.

A fix would be to overwrite the `default.conf` with your `nginx_site.conf` or remove it on startup to make everything work as expected.

Cheers
Unkn0wn0x

**Comment by mhzawadi** [comment]
I have just setup the image on my pi swarm and it works fine, but I do run traefik v2.0 in front of all my web services. That could be the issue, will have a look with just a port exposed

**Comment by Unkn0wn0x** [comment]
I've created a sample, take a look:
1. `docker run -ti -d -p 80:80 --name invoiceplane --link invoiceplane-mysql:mysql -e HOST_URL=127.0.0.1 mhzawadi/invoiceplane`
2. `docker exec -it f9c6792fef99 /bin/sh`
3. You can see, that the `default.conf` will return a 404 on all requests, made to the container / nginx.
<img width="1012" alt="screenshot" src="https://user-images.githubusercontent.com/31123135/74984918-c64b1d00-5436-11ea-84c2-d03753c489cb.png">

**Comment by mhzawadi** [comment]
have just span up a copy on my mac and it works fine, I get the setup page and can see logs on the container. did the site.conf get setup with the HOST_URL as nginx should see that and use it to work out which server config it should use?

Docker setup
```
docker run --name invoiceplane-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -v /Users/mattho/docker_data/mysql:/var/lib/mysql -d mysql:5.6
docker run -ti -d -p 80:80 --name invoiceplane --link invoiceplane-mysql:mysql -e HOST_URL=127.0.0.1 mhzawadi/invoiceplane:v1.5.9.2
```

Logs:
```
172.17.0.1 - - [21/Feb/2020:09:37:07 +0000] "GET / HTTP/1.1" 307 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:07 +0000] "GET /index.php/welcome HTTP/1.1" 200 1667 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:07 +0000] "GET /assets/invoiceplane/css/welcome.css HTTP/1.1" 200 128876 "http://127.0.0.1/index.php/welcome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:07 +0000] "GET /assets/core/img/logo_400x200.png HTTP/1.1" 200 18661 "http://127.0.0.1/assets/invoiceplane/css/welcome.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:07 +0000] "GET /assets/core/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160 "http://127.0.0.1/assets/invoiceplane/css/welcome.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:07 +0000] "GET /favicon.ico HTTP/1.1" 404 835 "http://127.0.0.1/index.php/welcome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:16 +0000] "GET /index.php/setup HTTP/1.1" 307 5 "http://127.0.0.1/index.php/welcome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:16 +0000] "GET /index.php/setup/language HTTP/1.1" 200 7011 "http://127.0.0.1/index.php/welcome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:17 +0000] "GET /assets/core/js/dependencies.min.js HTTP/1.1" 200 378161 "http://127.0.0.1/index.php/setup/language" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"
172.17.0.1 - - [21/Feb/2020:09:37:17 +0000] "GET /assets/core/img/favicon.png HTTP/1.1" 200 4125 "http://127.0.0.1/index.php/setup/language" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "-"

**Comment by Unkn0wn0x** [comment]
Mhm, that's kinda strange.

I only modified the `IP_URL` to my public accessible domain (f. e. https://invoiceplane.example.com/), the `HOST_URL` is set by default in your `Dockerfile` to `127.0.0.1`, so no need to overwrite it, or am I wrong?

Do you have the `/etc/nginx/conf.d/default.conf` available in your container?

**Comment by mhzawadi** [comment]
thats the bit that might need more explanation, if you hand a host header to the container of 'invoiceplane.example.com' then the HOST_URL needs to match the domain.

If your expecting to hit the site on https://invoiceplane.example.com/ then 'HOST_URL' should have 'HOST_URL=invoiceplane.example.com' then nginx will see that and use the site.conf

as I hit the container on 127.0.0.1 it works, but I hit it with anything else it will get a 404 from nginx as the site doesn't exist.

**Comment by mhzawadi** [comment]
also see the compose https://github.com/mhzawadi/invoiceplane/blob/master/docker-compose.yml for a full example

**Comment by Unkn0wn0x** [comment]
Ah, now it looks more plausible to me. In my case, I'm running your docker container behind a reverse nginx proxy and pass requests as a upstream to the invoiceplane docker container.

That means, that I don't expose the invoiceplanes docker container to the public, which on the other hand means, it will listen per default to 127.0.0.1.

Now the `/etc/nginx/conf.d/default.conf` kicks in and prevents any request to be passed to the `/etc/nginx/conf.d/site.conf` virtual host.

Would't it be simplest solution to just delete the `default.conf` to make it work in every case?

Cheers
Unkn0wn0x

**Comment by mhzawadi** [comment]
have made 2 changes to the build, first is a version bump to 1.5.10. The upgrade should be just login, I hope.

The other change is that the default site now gets replaced with my own config, docker hub is building latest now. once its done can you have a look and close this if your happy?

**Comment by Unkn0wn0x** [comment]
Great job 👍 

I was happy before and it was not that big issue to me, since I added a hook to remove the `default.conf`, just to prevent some issues for other users.

Thanks so far
Unkn0wn0x
